export const sData = [{
    key: 1,
    userID: 88,
    name: "Amirthalingam  Elangovan",
    branch: "Chemical Engineering",
    email: "elango_ae@cadgraf.com",
    yearofPassing: 1976,
    occupation: "Managing Director",
    currentCompanyName: "Cadgraf Digitals Pvt Ltd",
    areaofExpertise: "Newspaper ERP, Workflow automation,",
    country: "India",
    photograph: null,
    orderID: 97,
    mobile: 9841023223,
    address: "Cadgraf Digitals Pvt Ltd, #2 Wheatcrofts Rd",
    street: "Nungambakkam",
    city: "Chennai",
    postalcode: 600034,
    joiningDate: "09/28/2019"
    },
    {
    key: 2,
    userID: 90,
    name: "Siva R",
    branch: "Bio Technology",
    email: "siva.rajendran@gmail.com",
    yearofPassing: 2004,
    occupation: "Sr divisional operations manager",
    currentCompanyName: "Indian railway",
    areaofExpertise: "Transportation",
    country: "India",
    photograph: null,
    orderID: 113,
    mobile: 9444366940,
    address: "145 b tungabhadra sterling road",
    street: "Nungambakkam",
    city: "Chennai",
    postalcode: 600034,
    joiningDate: "09/23/2019"
    }]